# Generated by Django 3.2.9 on 2021-11-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('created_time', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.DecimalField(decimal_places=0, default=1, max_digits=8)),
                ('product_price', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('addted_time', models.CharField(max_length=50)),
                ('item_cost', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_cart.shopping_cart')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
