# Generated by Django 3.2.5 on 2021-12-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_alter_shopping_cart_item_added_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart_item',
            name='added_time',
        ),
    ]
