# Generated by Django 3.2.5 on 2021-12-18 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_remove_shopping_cart_item_added_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart_item',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
