# Generated by Django 3.2.5 on 2021-12-18 19:00

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0012_auto_20211218_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 21, 0, 48, 519282)),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='user_name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 21, 0, 48, 525264)),
        ),
    ]
