# Generated by Django 3.2.5 on 2021-12-18 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0014_auto_20211218_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 21, 6, 19, 884193)),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 21, 6, 19, 885063)),
        ),
    ]
