# Generated by Django 3.2.5 on 2021-12-20 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
        ('shopping_cart', '0017_auto_20211220_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart_item',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='items',
            field=models.ManyToManyField(to='shopping_cart.Shopping_cart_item'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 19, 43, 0, 22492)),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 19, 43, 0, 20498)),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
