# Generated by Django 3.2.5 on 2021-12-27 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211227_1919'),
        ('shopping_cart', '0018_auto_20211220_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='start_date',
        ),
        migrations.AddField(
            model_name='shopping_cart_item',
            name='shopping_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_cart.shopping_cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 19, 18, 54, 551661)),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 19, 18, 54, 552658)),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
