# Generated by Django 3.2.5 on 2021-12-27 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0023_auto_20211227_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 19, 29, 47, 956716)),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 19, 29, 47, 956716)),
        ),
    ]
