# Generated by Django 3.2.9 on 2022-01-15 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0027_auto_20220102_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 10, 4, 53, 114474)),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 10, 4, 53, 125435)),
        ),
    ]
