# Generated by Django 3.2.9 on 2022-01-15 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0029_auto_20220115_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 10, 39, 50, 206088)),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 10, 39, 50, 216059)),
        ),
    ]
