# Generated by Django 3.2.5 on 2021-12-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_out', '0002_alter_check_out_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
