# Generated by Django 3.2.9 on 2022-01-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_out', '0004_address_order_new_orderitem_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_new',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem_new',
            name='Order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='check_out.order_new'),
        ),
    ]
