# Generated by Django 3.2.9 on 2022-01-15 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211227_1919'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('check_out', '0005_auto_20220115_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='check_out.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='order_new',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='order_new',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='orderitem_new',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='orderitem_new',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderitem_new',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem_new',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem_new',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem_new',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='order_new',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_new',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_new',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem_new',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='check_out.order_new'),
        ),
        migrations.AddField(
            model_name='orderitem_new',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem_new',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem_new',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='check_out.order_new'),
        ),
        migrations.AddField(
            model_name='order_new',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='check_out.customer'),
        ),
    ]
